# Generated by Django 3.1.3 on 2020-12-09 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kunde',
            old_name='Kundennr',
            new_name='name',
        ),
        migrations.CreateModel(
            name='Bestellung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bestellung', models.TextField()),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('kunde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.kunde')),
            ],
        ),
    ]
